### ISSUE TITLE
The following details are required when implementing hardware

### ISSUE THREAD

**Issue by cheoljun99** [ToyotaInfoTech/RAMN#22]
Hello, I am a Korean college student currently studying the implementation of a vehicle hardware simulator. I need the following information to implement the hardware in your project.

Could you kindly answer me?

- What board in single pcs or in panel? If panel, plz advice your prefered panel way, and notice that we have MOQ for panel, which is 5.
- Board material
- TG
- Board thickness
- Solder mask and silkscreen color
- Surface finish
- Copper thickness(inner and outer)
- Via process: tent vias/ plug vias by solder mask ink/expose vias
- If there's any other special requirement, plz let me know at the same time.

**Comment by CamilleTTT** [comment]
I saw that you closed the issue, but just in case:

We typically ask for the following:
- FR4 board, 1.6mm thickness. Tg depends on your intended application - the boards do not get very hot in typical operating conditions.
- Flash gold surface finish.
- Black solder mask, white silkscreen (note that some PCB fabs may prefer that you use a green solder mask to achieve required tolerances).
- 35u copper thickness (it's a two-layer board so only outer copper).
- Via process: Whatever the PCB fab recommends. By default the "tent vias" option of KiCAD is selected.
- Special requirement: solder the pin header on the Adafruit screen, if it is required (it is provided unsoldered by Adafruit).

GERBER files are provided only as single pieces. If possible, you should ask the PCB fab to panelized them to reduce cost. Note that component references do not repeat for expansions (1_screens to 5_debugger use the same BOM), but they repeat for the main board (0_ramn), so some fabs may complain if you want to panelize 0_ramn with another board. Therefore it is better to ask for two orders: One for the 0_ramn main board as a single piece, and one for the expansions (1_screens to 5_debugger) as a panel of 5 pieces.
